/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CMS1500Data } from './types';

export const INITIAL_CMS_DATA: CMS1500Data = {
  programType: '',
  insuredId: '',
  patientName: '',
  patientBirthDate: '',
  patientSex: '',
  insuredName: '',
  patientAddress: {
    street: '',
    city: '',
    state: '',
    zipCode: '',
    phone: '',
  },
  patientRelationship: '',
  insuredAddress: {
    street: '',
    city: '',
    state: '',
    zipCode: '',
    phone: '',
  },
  otherInsuredName: '',
  otherInsuredPolicy: '',
  conditionRelatedTo: {
    employment: false,
    autoAccident: false,
    place: '',
    otherAccident: false,
  },
  insuredGroupNumber: '',
  insuredBirthDate: '',
  insuredSex: '',
  insuredEmployer: '',
  insuredPlanName: '',
  otherHealthPlan: false,
  patientSignatureDate: '',
  insuredSignatureAuthorized: false,
  dateOfIllness: '',
  dateOfIllnessQual: '',
  otherDate: '',
  otherDateQual: '',
  unableToWorkFrom: '',
  unableToWorkTo: '',
  referringProviderName: '',
  referringProviderQual: '',
  referringProviderNpi: '',
  hospFrom: '',
  hospTo: '',
  additionalClaimInfo: '',
  outsideLab: false,
  outsideLabCharges: '',
  diagnosisCodeIcd: '0',
  diagnosisCodes: ['', '', '', '', '', '', '', '', '', '', '', ''],
  resubmissionCode: '',
  resubmissionReference: '',
  priorAuthNumber: '',
  serviceLines: [
    {
      fromDate: '',
      toDate: '',
      placeOfService: '',
      emergency: false,
      cptCode: '',
      modifier: '',
      diagnosisPointer: '',
      charges: '',
      daysOrUnits: '',
      renderingProviderNpi: '',
    },
  ],
  taxId: '',
  taxIdType: '',
  patientAccountNo: '',
  acceptAssignment: true,
  totalCharge: '',
  amountPaid: '',
  physicianSignatureDate: '',
  facilityInfo: {
    name: '',
    street: '',
    city: '',
    state: '',
    zipCode: '',
    npi: '',
  },
  billingProviderInfo: {
    name: '',
    street: '',
    city: '',
    state: '',
    zipCode: '',
    phone: '',
    npi: '',
    otherId: '',
  },
};
